std = 'lua54'

globals = {}


exclude_files = {
	'packages/**',
}


allow_defined_top	= true
allow_defined		= false


ignore = {
	'631',	-- line is too long
}


files['../shared/Types.lua'] = {ignore = {'212', '241', '131', '614'}}
	-- this is a types definition file, autogenerated by UE4SS
	-- so ignore it's problem,  we need it to define globals
